### ISSUE TITLE
How to use this.added?

### ISSUE THREAD

**Issue by jaredloson** [jamauro/pub-sub#10]
I'm trying to transform some data in a publication like this:

```
Meteor.publish.once('someCollection.user', function () {
  const userId = this.userId

  SomeCollection.find({ userId }).observeChanges({
    added: (id, fields) => {
      this.added('leagues', id, customTransformFn(fields, userId))
    },
  })

  this.ready()
})
```

The above works when using `Meteor.publish`, but with `Meteor.publish.once` I always get an empty array when subscribing on the client. Is there a different way I should be approaching this?

**Comment by jamauro** [comment]
Hmm I haven't tried it but I think returning the cursor with your transform would work, e.g.

```js
return SomeCollection.find({ userId }, { transform: ... })
```

**Comment by jaredloson** [comment]
Oh wow, I didn't realize we could pass a transform function, yeah that seems to work, thanks! I'm still a bit confused on how to use `this.added`, but I'll go ahead and close this issue.
